spring:
  datasource:
    url: ${QA_DB_URL}
    username: ${QA_DB_USERNAME}
    password: ${QA_DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${QA_JWT_SECRET}
  expiration: 28800000

logging:
  level:
    root: INFO