spring:
  application:
    name: revHub

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

  api-docs:
    enabled: true

logging:
  level:
    root: INFO